// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tom F. (https://github.com/tomtom215/duckdb-behavioral)

//! # `behavioral` — Behavioral Analytics Extension for `DuckDB`
//!
//! Provides seven functions for behavioral analytics, inspired by `ClickHouse`'s
//! behavioral analytics functions but designed for `DuckDB`'s SQL dialect.
//!
//! ## Functions
//!
//! | Function | Type | Description |
//! |----------|------|-------------|
//! | `sessionize(ts, gap)` | Window | Assigns session IDs based on inactivity gaps |
//! | `retention(c1, ..., cN)` | Aggregate | Cohort retention analysis |
//! | `window_funnel(window, ts, c1, ..., cN)` | Aggregate | Conversion funnel analysis |
//! | `sequence_match(pattern, ts, c1, ..., cN)` | Aggregate | Pattern matching over event sequences |
//! | `sequence_count(pattern, ts, c1, ..., cN)` | Aggregate | Counts pattern matches in event sequences |
//! | `sequence_match_events(pattern, ts, c1, ..., cN)` | Aggregate | Returns matched step timestamps |
//! | `sequence_next_node(dir, base, ts, val, bc, e1, ..., eN)` | Aggregate | Next event after pattern match |
//!
//! ## Installation
//!
//! ```sql
//! INSTALL behavioral FROM community;
//! LOAD behavioral;
//! ```

pub mod common;
pub mod pattern;
pub mod retention;
pub mod sequence;
pub mod sequence_next_node;
pub mod sessionize;
pub mod window_funnel;

mod ffi;

// Extension entry point generated by `quack_rs::entry_point_v2!`.
//
// This macro generates the `#[no_mangle] unsafe extern "C"` function named
// `behavioral_init_c_api` that DuckDB calls when loading the extension.
// It handles API initialization, connection management, and error reporting
// — replacing ~80 lines of hand-rolled unsafe code with a single macro call.
//
// The closure receives a `&Connection` implementing the `Registrar` trait,
// providing a version-agnostic API for registering all extension components.
quack_rs::entry_point_v2!(behavioral_init_c_api, |con| {
    // Safety: `con` is a valid Connection provided by the entry_point_v2!
    // macro via duckdb_connect. The macro's closure runs in an unsafe context.
    ffi::register_all(con)
});
